Delete extractors-tesseract directory Fixes #3
clowder-framework/extractors-cv pull request #4
Opened 2022-06-02 21:04 UTC by ddey2

2022-06-02 21:41 UTC, lmarini requested changes
Can you add an entry to the changelog with the link to the new repository?

2022-06-02 21:41 UTC, robkooper approved these changes

2022-06-03 20:55 UTC, ddey2 commented
> Can you add an entry to the changelog with the link to the new repository?

Added entry to changelog.

2022-06-03 20:56 UTC, lmarini approved these changes

2022-06-03 20:56 UTC, merged